### ISSUE TITLE
Bad EOF?

### ISSUE THREAD

**Issue by CarlosMed** [kisscool-fr/ghibliql#1]
I keep getting this issue when navigating to https://ghibliql.herokuapp.com
`"message": "Syntax Error: Unexpected <EOF>"`
and CORS issue when trying to call it in a GraphQL playground.

**Comment by kisscool-fr** [comment]
Thanks for the notice, this happen when there is no GraphQL query, you should try with something like:

`POST / HTTP/1.1`
`Host: ghibliql.herokuapp.com`
`Content-Type: application/json`
`Content-Length: 126`
`{"query":"{
  films {
    id
    title
    director
    release_date
    people {
      id
      name
    }
  }
}"}`

I'll add some code to strengthen this a little bit, thanks for the feedback 👍 
And I'll have a look about the CORS.
