### ISSUE TITLE
Image / Movie Banner for Films

### ISSUE THREAD

**Issue by khatrirohan** [kisscool-fr/ghibliql#3]
I am unable to fetch image or movie_banner for films query. Is it present?

Here is the schema that was generated

type Film {
    "Description of the film"
    description: String
    "Director of the film"
    director: String
    "Unique identifier representing a specific film"
    id: String!
    "Locations found in film"
    locations: [Location]
    "Original title of the film"
    original_title: String
    "Orignal title in romanised form"
    original_title_romanised: String
    "People found in film"
    people: [People]
    "Producer of the film"
    producer: String
    "Release year of film"
    release_date: String
    "Rotten Tomato score of film"
    rt_score: String
    "Running time of the film in minutes"
    running_time: String
    "Species found in film"
    species: [Specie]
    "Title of the film"
    title: String
    "URL of film"
    url: String
    "Vehicles found in film"
    vehicles: [Vehicle]
}

**Comment by kisscool-fr** [comment]
Hi, thanks for mentionning this.

Fields `movie_banner` and `image` are available since commit 01d5b3bd 
I can find these fields into the generated schema (at least with Insomnia, haven't try with other)

I just push a small unrelated update on prod, maybe it help refreshing some things, could you confirm it's working now ?
Thanks 🙏🏼

**Comment by khatrirohan** [comment]
> Hi, thanks for mentionning this.
> 
> Fields `movie_banner` and `image` are available since commit [01d5b3b](https://github.com/kisscool-fr/ghibliql/commit/01d5b3bd872123e190ee419e680e65ea967c3cd6) I can find these fields into the generated schema (at least with Insomnia, haven't try with other)
> 
> I just push a small unrelated update on prod, maybe it help refreshing some things, could you confirm it's working now ? Thanks 🙏🏼

yes those fields are coming now. Thanks.
